export const mockSearchResults = [
  {
    id: 1,
    title: "Blinding Lights",
    artist: "The Weeknd",
    album: "After Hours",
    duration: "3:22",
    popularity: 95,
  },
  {
    id: 2,
    title: "Shape of You",
    artist: "Ed Sheeran",
    album: "÷ (Divide)",
    duration: "3:53",
    popularity: 88,
  },
  {
    id: 3,
    title: "Someone Like You",
    artist: "Adele",
    album: "21",
    duration: "4:45",
    popularity: 92,
  },
  {
    id: 4,
    title: "Bohemian Rhapsody",
    artist: "Queen",
    album: "A Night at the Opera",
    duration: "5:55",
    popularity: 97,
  },
  {
    id: 5,
    title: "Watermelon Sugar",
    artist: "Harry Styles",
    album: "Fine Line",
    duration: "2:54",
    popularity: 85,
  },
];

export const queueStats = {
  main: { totalVotes: 22, activeUsers: 12, songsPlayed: 45 },
  party: { totalVotes: 59, activeUsers: 8, songsPlayed: 23 },
  chill: { totalVotes: 30, activeUsers: 5, songsPlayed: 18 },
};

export const mainData = {
  main: [
    {
      id: 101,
      title: "Anti-Hero",
      artist: "Taylor Swift",
      votes: 24,
      addedBy: "Sarah M.",
      timeAdded: "2 min ago",
      status: "playing",
    },
    {
      id: 102,
      title: "As It Was",
      artist: "Harry Styles",
      votes: 18,
      addedBy: "Mike J.",
      timeAdded: "5 min ago",
      status: "queued",
    },
    {
      id: 103,
      title: "Unholy",
      artist: "Sam Smith ft. Kim Petras",
      votes: 15,
      addedBy: "Emma K.",
      timeAdded: "8 min ago",
      status: "queued",
    },
    {
      id: 104,
      title: "Flowers",
      artist: "Miley Cyrus",
      votes: 12,
      addedBy: "Alex R.",
      timeAdded: "12 min ago",
      status: "queued",
    },
    {
      id: 105,
      title: "Stay",
      artist: "The Kid LAROI & Justin Bieber",
      votes: 9,
      addedBy: "Chris L.",
      timeAdded: "15 min ago",
      status: "queued",
    },
  ],
  party: [
    {
      id: 201,
      title: "Uptown Funk",
      artist: "Mark Ronson ft. Bruno Mars",
      votes: 31,
      addedBy: "DJ Alex",
      timeAdded: "1 min ago",
      status: "playing",
    },
    {
      id: 202,
      title: "Can't Stop the Feeling!",
      artist: "Justin Timberlake",
      votes: 28,
      addedBy: "Lisa P.",
      timeAdded: "4 min ago",
      status: "queued",
    },
  ],
  chill: [
    {
      id: 301,
      title: "Circles",
      artist: "Post Malone",
      votes: 16,
      addedBy: "Maya S.",
      timeAdded: "3 min ago",
      status: "playing",
    },
    {
      id: 302,
      title: "Levitating",
      artist: "Dua Lipa",
      votes: 14,
      addedBy: "Tom W.",
      timeAdded: "7 min ago",
      status: "queued",
    },
  ],
};
